/* AUTO-GENERATED by generate-sw-hashes.js on every commit. Do not edit by hand. */
(function (g) {
  g.GBE_BUILD = '2026.09.12-2128.7daaa3a';
  try { console.log('[build] GBE ' + g.GBE_BUILD); } catch (e) {}
})(typeof window !== "undefined" ? window : this);
