/* AUTO-GENERATED by generate-sw-hashes.js on every commit. Do not edit by hand. */
(function (g) {
  g.GBE_BUILD = '2026.07.15-1257.0b554d4';
  try { console.log('[build] GBE ' + g.GBE_BUILD); } catch (e) {}
})(typeof window !== "undefined" ? window : this);
